### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [tisron/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by tisron** [comment]
Ok, so I added the viewport meta tag with "width=device-width, initial-scale=1" as properties. This kept the app from zooming out my HTC One. 

It's surprising because I thought Bootstrap handled all of responsiveness of the app. 

How does is look on your device now?

**Comment by BillyMassey** [comment]
Thumbs up.  I just checked your Github and it looks like you added the viewport meta tag just as expected.  Keep up the awesome work coding.
